---
- name: EC2 Test Example
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    st_type: running
  tasks:
  - name: Install Docker Module for Python
    apt:
      name: python3-pip
  - name: Install Docker Module for Python
    pip:
      name: boto  
  - name: create ec2 instance
    ec2:
      key_name: raviohio
      instance_type: t2.micro
      image: ami-024e6efaf93d85776
      wait: yes
      group: webserver
      count: 1
      vpc_subnet_id: subnet-09ff655fb2c442ab8
      assign_public_ip: yes
      state: "{{ st_type }}"
