---
- name: Create EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: False

  
  tasks:
    - name: run custom module
      my_test:
       new: "true"
       name: "hello"
    - name: run custom module
      custom_file:
       name: "a.txt"
       state: present
    