---
- name: Create EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: False

  environment:
    AWS_ACCESS_KEY_ID: "YOUR_ACCESS_KEY"
    AWS_SECRET_ACCESS_KEY: "YOUR_SECRET_KEY"
    AWS_DEFAULT_REGION: "us-east-1"
  vars:
    region: "us-east-1"  # Update with your desired region
    instance_type: "t2.micro"  # Update with your desired instance type
    image_id: "ami-xxxxxxxxxxxxxxxxx"  # Update with the desired AMI ID
    security_group: "my-security-group"  # Update with the desired security group name
    key_pair: "my-key-pair"  # Update with the desired key pair name
    subnet_id: "subnet-xxxxxxxxxxxxxx" 
  tasks:
    - name: Create EC2 Instance
      ec2:
        region: "{{ region }}"
        key_name: "{{ key_pair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image_id }}"
        wait: yes
        group: "{{ security_group }}"
        vpc_subnet_id: "{{ subnet_id }}"
        assign_public_ip: yes
        count: 1
      register: ec2_instance

    - name: Print EC2 Instance Details
      debug:
        var: ec2_instance
