---
- name: install some package
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - tree
  - nginx
  - gfgfg

- name: copy file
  copy:
    src: abc.txt
    dest: /tmp/abc.txt
    
- name: copy file
  command:
   cmd: "ls -lrt /usr/bin"
