---
- name: install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true
- name: install docker package
  apt:
    name: docker.io
    state: latest
- name: install docker for python
  pip:
    name: docker

# - name: start docker container
#   command: docker run -itd --name=ex1 ubuntu
- name: Create a ex1 container
  docker_container:
    name: ex1
    image: ubuntu

- name: check the status docker container
  command: docker inspect ex1 | grep "Running"